[workspace]
resolver = "2"
members = [
    "crates/protocol",
    "crates/antenna",
    "crates/client/*",
    "crates/signaling-server",
    "crates/integration-tests",
    "crates/arbitrary-tests",
    "example/*",
]

[workspace.package]
rust-version = "1.89.0"

[workspace.dependencies.antenna]
version = "0.1.0"
path = "crates/antenna"

[workspace.dependencies.antenna-protocol]
version = "0.1.0"
path = "crates/protocol"

[workspace.dependencies.antenna-client-web]
version = "0.1.0"
path = "crates/client/web"
default-features = false

[workspace.dependencies.antenna-client-native]
version = "0.1.0"
path = "crates/client/native"
default-features = false

[workspace.dependencies.antenna-client-shared]
version = "0.1.0"
path = "crates/client/shared"

[workspace.dependencies.anyhow]
version = "1.0.101"

[workspace.dependencies.serde]
version = "1.0.228"
features = ["derive"]

[workspace.dependencies.serde_json]
version = "1.0.149"

[workspace.dependencies.futures]
version = "0.3.32"

[workspace.dependencies.wasm-bindgen]
version = "0.2"

[workspace.dependencies.wasm-bindgen-futures]
version = "0.4"

[workspace.dependencies.js-sys]
version = "0.3"

[workspace.dependencies.serde-wasm-bindgen]
version = "0.6"

[workspace.dependencies.biscuit-auth]
version = "6.0.0"
features = ["wasm"]

[workspace.dependencies.base64]
version = "0.22"

[workspace.dependencies.rand]
version = "0.8"

[workspace.dependencies.getrandom]
version = "0.2"
features = ["js"]

[workspace.dependencies.axum]
version = "0.8.9"
features = ["ws"]

[workspace.dependencies.tokio]
version = "1.0.0"
features = ["full"]

[workspace.dependencies.tokio-tungstenite]
version = "0.24"

[workspace.dependencies.webrtc]
version = "0.11"

[workspace.dependencies.bytes]
version = "1"

[workspace.dependencies.send_wrapper]
version = "0.6"

[workspace.dependencies.tempfile]
version = "3"

[workspace.dependencies.async-trait]
version = "0.1.89"

[workspace.dependencies.web-sys]
version = "0.3"
features = [
    "RtcPeerConnection",
    "RtcConfiguration",
    "RtcDataChannel",
    "RtcDataChannelEvent",
    "RtcDataChannelInit",
    "RtcDataChannelState",
    "RtcDataChannelType",
    "RtcSdpType",
    "RtcSignalingState",
    "RtcSessionDescription",
    "RtcSessionDescriptionInit",
    "RtcIceServer",
    "RtcIceConnectionState",
    "RtcIceGatheringState",
    "MessageEvent",
    "ErrorEvent",
    "console",
    "Window",
    "Storage",
    "WebSocket",
]

[profile.release]
opt-level = "z"
lto = true
