[workspace]
resolver = "2"
members = [
    "crates/protocol",
    "crates/antenna",
    "crates/shared",
    "crates/client/*",
    "crates/signaling-server",
    "example/*",
]

[workspace.package]
rust-version = "1.89.0"

[workspace.dependencies.antenna]
path = "crates/antenna"

[workspace.dependencies.antenna-protocol]
path = "crates/protocol"

[workspace.dependencies.antenna-shared]
path = "crates/shared"

[workspace.dependencies.antenna-client-web]
path = "crates/client/web"

[workspace.dependencies.antenna-client-native]
path = "crates/client/native"

[workspace.dependencies.antenna-client-shared]
path = "crates/client/shared"

[workspace.dependencies.antenna-signaling-server]
path = "crates/signaling-server"

[workspace.dependencies.anyhow]
version = "1.0.101"

[workspace.dependencies.serde]
version = "1.0.228"
features = ["derive"]

[workspace.dependencies.serde_json]
version = "1.0.149"

[workspace.dependencies.futures]
version = "0.3.32"

# WASM dependencies
[workspace.dependencies.wasm-bindgen]
version = "0.2"

[workspace.dependencies.wasm-bindgen-futures]
version = "0.4"

[workspace.dependencies.js-sys]
version = "0.3"

[workspace.dependencies.serde-wasm-bindgen]
version = "0.6"

[workspace.dependencies.biscuit-auth]
version = "6.0.0"
features = ["wasm"]

[workspace.dependencies.base64]
version = "0.22"

[workspace.dependencies.rand]
version = "0.8"

[workspace.dependencies.web-sys]
version = "0.3"
features = [
    "RtcPeerConnection",
    "RtcConfiguration",
    "RtcDataChannel",
    "RtcDataChannelEvent",
    "RtcDataChannelInit",
    "RtcDataChannelState",
    "RtcDataChannelType",
    "RtcSdpType",
    "RtcSignalingState",
    "RtcSessionDescription",
    "RtcSessionDescriptionInit",
    "RtcIceServer",
    "RtcIceConnectionState",
    "RtcIceGatheringState",
    "MessageEvent",
    "ErrorEvent",
    "console",
]

[profile.release]
opt-level = "z"
lto = true
