[package]
name = "antenna-client-native"
version = "0.1.1"
edition = "2024"
rust-version.workspace = true
description = "Native rust (over Tokio & webrtc-rs) platform implementation for the antenna P2P mesh protocol."
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[features]
default = ["signaling-client"]
signaling-client = ["dep:tokio-tungstenite"]

[dependencies]
antenna-protocol.workspace = true
antenna-client-shared.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
async-trait.workspace = true
tokio.workspace = true
tokio-tungstenite = { workspace = true, optional = true }
webrtc.workspace = true
bytes.workspace = true
