[package]
name = "shell-chat"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "native-chat"
path = "src/main.rs"

[dependencies]
antenna = { path = "../../crates/antenna", default-features = false, features = ["native"] }
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
