[package]
name = "antenna-client-web"
version = "0.1.1"
edition = "2024"
rust-version.workspace = true
description = "Web-over-WASM platform implementation for the antenna P2P mesh protocol."
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[features]
default = ["signaling-client"]
signaling-client = []

[dependencies]
antenna-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
js-sys.workspace = true
serde-wasm-bindgen.workspace = true
web-sys.workspace = true
anyhow.workspace = true
futures.workspace = true
biscuit-auth.workspace = true
base64.workspace = true
getrandom.workspace = true
async-trait.workspace = true
antenna-client-shared.workspace = true
send_wrapper.workspace = true

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]
