[package]
name = "antenna-client-shared"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
description = "Shared tlayer used by antenna platform implementation."
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
antenna-protocol.workspace = true
anyhow.workspace = true
serde.workspace = true
